export enum GradientType {
  FATHER = "FATHER",
  MOTHER = "MOTHER",
  SIBLING = "SIBLING",
  CHILD = "CHILD",
  SPOUSE = "SPOUSE",
  GRANDPARENT = "GRANDPARENT",
  GRANDCHILD = "GRANDCHILD",
  AUNT = "AUNT",
  UNCLE = "UNCLE",
  COUSIN = "COUSIN",
  NEPHEW = "NEPHEW",
  NIECE = "NIECE",
  FRIEND = "FRIEND",
  OTHER = "OTHER",

}
